all:
  hosts:
    dc1:
      ansible_host: 192.168.100.250
      ansible_user: Administrateur
      ansible_password: 85432196Alex*
      ansible_connection: winrm
      ansible_winrm_transport: ssl
      ansible_port: 5986
      ansible_winrm_server_cert_validation: ignore

    fs1:
      ansible_host: 192.168.100.251
      ansible_user: Administrateur
      ansible_password: 85432196Alex*
      ansible_connection: winrm
      ansible_winrm_transport: ssl
      ansible_port: 5986
      ansible_winrm_server_cert_validation: ignore

    web1:
      ansible_host: 192.168.100.252
      ansible_user: Administrateur
      ansible_password: 85432196Alex*
      ansible_connection: winrm
      ansible_winrm_transport: ssl
      ansible_port: 5986
      ansible_winrm_server_cert_validation: ignore
