---
- name: Création du dossier, ACL et partage réseau
  hosts: fs1
  gather_facts: no
  tasks:
    - name: Créer le dossier D:\Partage_DATAS
      ansible.windows.win_file:
        path: D:\Partage_DATAS
        state: directory

    - name: Donner tous les droits NTFS au groupe "Utilisateurs du domaine"
      ansible.windows.win_acl:
        path: D:\Partage_DATAS
        user: "HEXALTECH\\Utilisateurs du domaine"
        rights: FullControl
        type: allow
        state: present

    - name: Créer le partage réseau SMB Partage_DATAS
      ansible.windows.win_share:
        name: Partage_DATAS
        path: D:\Partage_DATAS
        full: "HEXALTECH\\Utilisateurs du domaine"
        state: present
