- name: Créer un raccourci AnyDesk pour tous les utilisateurs
  hosts: all
  gather_facts: no
  vars:
    anydesk_path: C:/Install/AnyDesk
    shortcut_name: AnyDesk.lnk
    public_desktop: C:/Users/Public/Desktop

  tasks:
    - name: Créer le dossier pour AnyDesk
      win_file:
        path: "{{ anydesk_path }}"
        state: directory

    - name: Copier l'exécutable AnyDesk sur le serveur
      win_copy:
        src: /root/ansible/02_Partage_DATAS/files/AnyDesk.exe
        dest: "{{ anydesk_path }}/AnyDesk.exe"

    - name: Créer un raccourci sur le bureau public
      win_shell: |
        $target = "{{ anydesk_path }}\AnyDesk.exe"
        $shortcutPath = [System.IO.Path]::Combine("{{ public_desktop }}", "{{ shortcut_name }}")
        $WshShell = New-Object -ComObject WScript.Shell
        $shortcut = $WshShell.CreateShortcut($shortcutPath)
        $shortcut.TargetPath = $target
        $shortcut.WorkingDirectory = "{{ anydesk_path }}"
        $shortcut.IconLocation = $target
        $shortcut.Save()
