---
- name: Gestion Active Directory Hexaltech
  hosts: dc1
  gather_facts: no
  vars_files:
    - /root/Ansible_WindowsServer/group_vars/all/vault.yml

  tasks:

    - name: Créer l'OU Hexaltech
      win_shell: |
        if (-not (Get-ADOrganizationalUnit -Filter "Name -eq 'Hexaltech'" -ErrorAction SilentlyContinue)) {
          New-ADOrganizationalUnit -Name "Hexaltech" -Path "DC=hexaltech,DC=lan"
        }
      args:
        executable: powershell

    - name: Créer les groupes AD dans l'OU Hexaltech
      win_shell: |
        if (-not (Get-ADGroup -Filter "Name -eq '{{ item }}'" -ErrorAction SilentlyContinue)) {
          New-ADGroup -Name "{{ item }}" -GroupScope Global -Path "OU=Hexaltech,DC=hexaltech,DC=lan"
        }
      loop:
        - Groupe1
        - Groupe2
      args:
        executable: powershell

    - name: Créer les utilisateurs dans l'OU Hexaltech
      win_shell: |
        $Password = ConvertTo-SecureString "{{ windows_server_password_active_directory }}" -AsPlainText -Force
        if (-not (Get-ADUser -Filter "SamAccountName -eq '{{ item.username }}'" -ErrorAction SilentlyContinue)) {
          New-ADUser -Name "{{ item.username }}" -SamAccountName "{{ item.username }}" -AccountPassword $Password -Enabled $true -Path "OU=Hexaltech,DC=hexaltech,DC=lan"
        }
      loop:
        - { username: "User1", group: "Groupe1" }
        - { username: "User2", group: "Groupe2" }
      args:
        executable: powershell

    - name: Ajouter les utilisateurs aux groupes
      win_shell: |
        Add-ADGroupMember -Identity "{{ item.group }}" -Members "{{ item.username }}"
      loop:
        - { username: "User1", group: "Groupe1" }
        - { username: "User2", group: "Groupe2" }
      args:
        executable: powershell
