---
- name: Déployer Active Directory sur DC1
  hosts: dc1
  gather_facts: no
  vars:
    domain_name: "hexaltech.lan"
    safe_mode_password: "votre_mot_de_passe"
  tasks:
    - name: Installer le rôle AD DS
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promouvoir le serveur en contrôleur de domaine
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "Administrateur"
        domain_admin_password: "{{ safe_mode_password }}"
        safe_mode_password: "{{ safe_mode_password }}"
        state: domain
        install_dns: yes
