---
- name: Déployer Active Directory sur DC1
  hosts: dc1
  gather_facts: no
  vars_files:
    - /root/Ansible_WindowsServer/group_vars/all/vault.yml   # fichier Vault

  tasks:
    - name: Installer le rôle AD DS
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promouvoir le serveur en contrôleur de domaine
      win_domain:
        dns_domain_name: "{{ domain_name }}"                     # depuis Vault
        domain_admin_user: "{{ domain_admin_user }}"             # depuis Vault
        domain_admin_password: "{{ domain_admin_password }}"     # depuis Vault
        safe_mode_password: "{{ domain_admin_password }}"       # idem Vault
        state: domain
        install_dns: yes
