---
- name: Déployer Active Directory et créer la forêt
  hosts: dc1
  gather_facts: no
  vars_files:
    - /root/Ansible_WindowsServer/group_vars/all/vault.yml   # contient tes variables sensibles

  tasks:
    - name: Installer le rôle AD DS
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promouvoir le serveur en contrôleur de domaine et créer la forêt
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"             # ex: hexaltech.lan
        safe_mode_password: "{{ domain_admin_password }}" # mot de passe DSRM
        install_dns: yes
        domain_netbios_name: "HEXALTECH"                 # NetBIOS (souvent le nom en majuscules)
        reboot: yes
